const noteBaseUrl = ''
// const noteBaseUrl = '/static/piano/'

export default {
	white:[
		{
		"id": 1,
		"name": "C2",
		"text": 1,
		"a": "..",
		"name2": "C",
		"keyCode": "49",
		"key": "1",
		"url": noteBaseUrl + "a49.mp3",
		"type": "white"
		},
		{
		"id": 2,
		"name": "D2",
		"text": 2,
		"a": "..",
		"name2": "D",
		"keyCode": "50",
		"key": "2",
		"url": noteBaseUrl + "a50.mp3",
		"type": "white"
		},
		{
		"id": 3,
		"name": "E2",
		"text": 3,
		"a": "..",
		"name2": "E",
		"keyCode": "51",
		"key": "3",
		"url": noteBaseUrl + "a51.mp3",
		"type": "white"
		},
		{
		"id": 4,
		"name": "F2",
		"text": 4,
		"a": "..",
		"name2": "F",
		"keyCode": "52",
		"key": "4",
		"url": noteBaseUrl + "a52.mp3",
		"type": "white"
		},
		{
		"id": 5,
		"name": "G2",
		"text": 5,
		"a": "..",
		"name2": "G",
		"keyCode": "53",
		"key": "5",
		"url": noteBaseUrl + "a53.mp3",
		"type": "white"
		},
		{
		"id": 6,
		"name": "A2",
		"text": 6,
		"a": "..",
		"name2": "A",
		"keyCode": "54",
		"key": "6",
		"url": noteBaseUrl + "a54.mp3",
		"type": "white"
		},
		{
		"id": 7,
		"name": "B2",
		"text": 7,
		"a": "..",
		"name2": "B",
		"keyCode": "55",
		"key": "7",
		"url": noteBaseUrl + "a55.mp3",
		"type": "white"
		},
		{
		"id": 8,
		"name": "C3",
		"text": 1,
		"a": ".",
		"name2": "c",
		"keyCode": "56",
		"key": "8",
		"url": noteBaseUrl + "a56.mp3",
		"type": "white"
		},
		{
		"id": 9,
		"name": "D3",
		"text": 2,
		"a": ".",
		"name2": "d",
		"keyCode": "57",
		"key": "9",
		"url": noteBaseUrl + "a57.mp3",
		"type": "white"
		},
		{
		"id": 10,
		"name": "E3",
		"text": 3,
		"a": ".",
		"name2": "e",
		"keyCode": "48",
		"key": "0",
		"url": noteBaseUrl + "a48.mp3",
		"type": "white"
		},
		{
		"id": 11,
		"name": "F3",
		"text": 4,
		"a": ".",
		"name2": "f",
		"keyCode": "81",
		"key": "Q",
		"url": noteBaseUrl + "a81.mp3",
		"type": "white",
		},
		{
		"id": 12,
		"name": "G3",
		"text": 5,
		"a": ".",
		"name2": "g",
		"keyCode": "87",
		"key": "W",
		"url": noteBaseUrl + "a87.mp3",
		"type": "white"
		},
		{
		"id": 13,
		"name": "A3",
		"text": 6,
		"a": ".",
		"name2": "a",
		"keyCode": "69",
		"key": "E",
		"url": noteBaseUrl + "a69.mp3",
		"type": "white"
		},
		{
		"id": 14,
		"name": "B3",
		"text": 7,
		"a": ".",
		"name2": "b",
		"keyCode": "82",
		"key": "R",
		"url": noteBaseUrl + "a82.mp3",
		"type": "white"
		},
		{
		"id": 15,
		"name": "C4",
		"text": 1,
		"a": "",
		"name2": "c",
		"name3": "1",
		"red": true,
		"keyCode": "84",
		"key": "T",
		"url": noteBaseUrl + "a84.mp3",
		"type": "white"
		},
		{
		"id": 16,
		"name": "D4",
		"text": 2,
		"a": "",
		"name2": "d",
		"name3": "1",
		"keyCode": "89",
		"key": "Y",
		"url": noteBaseUrl + "a89.mp3",
		"type": "white"
		},
		{
		"id": 17,
		"name": "E4",
		"text": 3,
		"a": "",
		"name2": "e",
		"name3": "1",
		"keyCode": "85",
		"key": "U",
		"url": noteBaseUrl + "a85.mp3",
		"type": "white"
		},
		{
		"id": 18,
		"name": "F4",
		"text": 4,
		"a": "",
		"name2": "f",
		"name3": "1",
		"keyCode": "73",
		"key": "I",
		"url": noteBaseUrl + "a73.mp3",
		"type": "white"
		},
		{
		"id": 19,
		"name": "G4",
		"text": 5,
		"a": "",
		"name2": "g",
		"name3": "1",
		"keyCode": "79",
		"key": "O",
		"url": noteBaseUrl + "a79.mp3",
		"type": "white"
		},
		{
		"id": 20,
		"name": "A4",
		"text": 6,
		"a": "",
		"name2": "a",
		"name3": "1",
		"keyCode": "80",
		"key": "P",
		"url": noteBaseUrl + "a80.mp3",
		"type": "white"
		},
		{
		"id": 21,
		"name": "B4",
		"text": 7,
		"a": "",
		"name2": "b",
		"name3": "1",
		"keyCode": "65",
		"key": "A",
		"url": noteBaseUrl + "a65.mp3",
		"type": "white"
		},
		{
		"id": 22,
		"name": "C5",
		"text": 1,
		"a": "1.",
		"name2": "c",
		"name3": "2",
		"keyCode": "83",
		"key": "S",
		"url": noteBaseUrl + "a83.mp3",
		"type": "white"
		},
		{
		"id": 23,
		"name": "D5",
		"text": 2,
		"a": "1.",
		"name2": "d",
		"name3": "2",
		"keyCode": "68",
		"key": "D",
		"url": noteBaseUrl + "a68.mp3",
		"type": "white"
		},
		{
		"id": 24,
		"name": "E5",
		"text": 3,
		"a": "1.",
		"name2": "e",
		"name3": "2",
		"keyCode": "70",
		"key": "F",
		"url": noteBaseUrl + "a70.mp3",
		"type": "white"
		},
		{
		"id": 25,
		"name": "F5",
		"text": 4,
		"a": "1.",
		"name2": "f",
		"name3": "2",
		"keyCode": "71",
		"key": "G",
		"url": noteBaseUrl + "a71.mp3",
		"type": "white"
		},
		{
		"id": 26,
		"name": "G5",
		"text": 5,
		"a": "1.",
		"name2": "g",
		"name3": "2",
		"keyCode": "72",
		"key": "H",
		"url": noteBaseUrl + "a72.mp3",
		"type": "white"
		},
		{
		"id": 27,
		"name": "A5",
		"text": 6,
		"a": "1.",
		"name2": "a",
		"name3": "2",
		"keyCode": "74",
		"key": "J",
		"url": noteBaseUrl + "a74.mp3",
		"type": "white"
		},
		{
		"id": 28,
		"name": "B5",
		"text": 7,
		"a": "1.",
		"name2": "b",
		"name3": "2",
		"keyCode": "75",
		"key": "K",
		"url": noteBaseUrl + "a75.mp3",
		"type": "white"
		},
		{
		"id": 29,
		"name": "C6",
		"text": 1,
		"a": "1..",
		"name2": "c",
		"name3": "3",
		"keyCode": "76",
		"key": "L",
		"url": noteBaseUrl + "a76.mp3",
		"type": "white"
		},
		{
		"id": 30,
		"name": "D6",
		"text": 2,
		"a": "1..",
		"name2": "d",
		"name3": "3",
		"keyCode": "90",
		"key": "Z",
		"url": noteBaseUrl + "a90.mp3",
		"type": "white"
		},
		{
		"id": 31,
		"name": "E6",
		"text": 3,
		"a": "1..",
		"name2": "e",
		"name3": "3",
		"keyCode": "88",
		"key": "X",
		"url": noteBaseUrl + "a88.mp3",
		"type": "white"
		},
		{
		"id": 32,
		"name": "F6",
		"text": 4,
		"a": "1..",
		"name2": "f",
		"name3": "3",
		"keyCode": "67",
		"key": "C",
		"url": noteBaseUrl + "a67.mp3",
		"type": "white"
		},
		{
		"id": 33,
		"name": "G6",
		"text": 5,
		"a": "1..",
		"name2": "g",
		"name3": "3",
		"keyCode": "86",
		"key": "V",
		"url": noteBaseUrl + "a86.mp3",
		"type": "white"
		},
		{
		"id": 34,
		"name": "A6",
		"text": 6,
		"a": "1..",
		"name2": "a",
		"name3": "3",
		"keyCode": "66",
		"key": "B",
		"url": noteBaseUrl + "a66.mp3",
		"type": "white"
		},
		{
		"id": 35,
		"name": "B6",
		"text": 7,
		"a": "1..",
		"name2": "b",
		"name3": "3",
		"keyCode": "78",
		"key": "N",
		"url": noteBaseUrl + "a78.mp3",
		"type": "white"
		}
  ],
	black:[{id: 37, name: 'C#2', keyCode: 'b49', key: '⇧<br>+<br>1', url: noteBaseUrl + 'b49.mp3', type: 'black'},
  {id: 38, name: 'D#2', keyCode: 'b50', key: '⇧<br>+<br>2', url: noteBaseUrl + 'b50.mp3', type: 'black'},
  {id: 39, name: 'F#2', keyCode: 'b52', key: '⇧<br>+<br>4', url: noteBaseUrl + 'b52.mp3', type: 'black'},
  {id: 40, name: 'G#2', keyCode: 'b53', key: '⇧<br>+<br>5', url: noteBaseUrl + 'b53.mp3', type: 'black'},
  {id: 41, name: 'A#2', keyCode: 'b54', key: '⇧<br>+<br>6', url: noteBaseUrl + 'b54.mp3', type: 'black'},
  {id: 42, name: 'C#3', keyCode: 'b56', key: '⇧<br>+<br>8', url: noteBaseUrl + 'b56.mp3', type: 'black'},
  {id: 43, name: 'D#3', keyCode: 'b57', key: '⇧<br>+<br>9', url: noteBaseUrl + 'b57.mp3', type: 'black'},
  {id: 44, name: 'F#3', keyCode: 'b81', key: '⇧<br>+<br>Q', url: noteBaseUrl + 'b81.mp3', type: 'black'},
  {id: 45, name: 'G#3', keyCode: 'b87', key: '⇧<br>+<br>W', url: noteBaseUrl + 'b87.mp3', type: 'black'},
  {id: 46, name: 'A#3', keyCode: 'b69', key: '⇧<br>+<br>E', url: noteBaseUrl + 'b69.mp3', type: 'black'},
  {id: 47, name: 'C#4', keyCode: 'b84', key: '⇧<br>+<br>T', url: noteBaseUrl + 'b84.mp3', type: 'black'},
  {id: 48, name: 'D#4', keyCode: 'b89', key: '⇧<br>+<br>Y', url: noteBaseUrl + 'b89.mp3', type: 'black'},
  {id: 49, name: 'F#4', keyCode: 'b73', key: '⇧<br>+<br>I', url: noteBaseUrl + 'b73.mp3', type: 'black'},
  {id: 50, name: 'G#4', keyCode: 'b79', key: '⇧<br>+<br>O', url: noteBaseUrl + 'b79.mp3', type: 'black'},
  {id: 51, name: 'A#4', keyCode: 'b80', key: '⇧<br>+<br>P', url: noteBaseUrl + 'b80.mp3', type: 'black'},
  {id: 52, name: 'C#5', keyCode: 'b83', key: '⇧<br>+<br>S', url: noteBaseUrl + 'b83.mp3', type: 'black'},
  {id: 53, name: 'D#5', keyCode: 'b68', key: '⇧<br>+<br>D', url: noteBaseUrl + 'b68.mp3', type: 'black'},
  {id: 54, name: 'F#5', keyCode: 'b71', key: '⇧<br>+<br>G', url: noteBaseUrl + 'b71.mp3', type: 'black'},
  {id: 55, name: 'G#5', keyCode: 'b72', key: '⇧<br>+<br>H', url: noteBaseUrl + 'b72.mp3', type: 'black'},
  {id: 56, name: 'A#5', keyCode: 'b74', key: '⇧<br>+<br>J', url: noteBaseUrl + 'b74.mp3', type: 'black'},
  {id: 57, name: 'C#6', keyCode: 'b76', key: '⇧<br>+<br>L', url: noteBaseUrl + 'b76.mp3', type: 'black'},
  {id: 58, name: 'D#6', keyCode: 'b90', key: '⇧<br>+<br>Z', url: noteBaseUrl + 'b90.mp3', type: 'black'},
  {id: 59, name: 'F#6', keyCode: 'b67', key: '⇧<br>+<br>C', url: noteBaseUrl + 'b67.mp3', type: 'black'},
  {id: 60, name: 'G#6', keyCode: 'b86', key: '⇧<br>+<br>V', url: noteBaseUrl + 'b86.mp3', type: 'black'},
  {id: 61, name: 'A#6', keyCode: 'b66', key: '⇧<br>+<br>B', url: noteBaseUrl + 'b66.mp3', type: 'black'}
]
}


export const NotesMap = [
  { name: 'C2', file: 'a49.mp3' },
  { name: 'D2', file: 'a50.mp3' },
  { name: 'E2', file: 'a51.mp3' },
  { name: 'F2', file: 'a52.mp3' },
  { name: 'G2', file: 'a53.mp3' },
  { name: 'A2', file: 'a54.mp3' },
  { name: 'B2', file: 'a55.mp3' },
  { name: 'C3', file: 'a56.mp3' },
  { name: 'D3', file: 'a57.mp3' },
  { name: 'E3', file: 'a48.mp3' },
  { name: 'F3', file: 'a81.mp3' },
  { name: 'G3', file: 'a87.mp3' },
  { name: 'A3', file: 'a69.mp3' },
  { name: 'B3', file: 'a82.mp3' },
  { name: 'C4', file: 'a84.mp3' },
  { name: 'D4', file: 'a89.mp3' },
  { name: 'E4', file: 'a85.mp3' },
  { name: 'F4', file: 'a73.mp3' },
  { name: 'G4', file: 'a79.mp3' },
  { name: 'A4', file: 'a80.mp3' },
  { name: 'B4', file: 'a65.mp3' },
  { name: 'C5', file: 'a83.mp3' },
  { name: 'D5', file: 'a68.mp3' },
  { name: 'E5', file: 'a70.mp3' },
  { name: 'F5', file: 'a71.mp3' },
  { name: 'G5', file: 'a72.mp3' },
  { name: 'A5', file: 'a74.mp3' },
  { name: 'B5', file: 'a75.mp3' },
  { name: 'C6', file: 'a76.mp3' },
  { name: 'D6', file: 'a90.mp3' },
  { name: 'E6', file: 'a88.mp3' },
  { name: 'F6', file: 'a67.mp3' },
  { name: 'G6', file: 'a86.mp3' },
  { name: 'A6', file: 'a66.mp3' },
  { name: 'B6', file: 'a78.mp3' },
  { name: 'C7', file: 'a77.mp3' },
  { name: 'C#2', file: 'b49.mp3' },
  { name: 'D#2', file: 'b50.mp3' },
  { name: 'F#2', file: 'b52.mp3' },
  { name: 'G#2', file: 'b53.mp3' },
  { name: 'A#2', file: 'b54.mp3' },
  { name: 'C#3', file: 'b56.mp3' },
  { name: 'D#3', file: 'b57.mp3' },
  { name: 'F#3', file: 'b81.mp3' },
  { name: 'G#3', file: 'b87.mp3' },
  { name: 'A#3', file: 'b69.mp3' },
  { name: 'C#4', file: 'b84.mp3' },
  { name: 'D#4', file: 'b89.mp3' },
  { name: 'F#4', file: 'b73.mp3' },
  { name: 'G#4', file: 'b79.mp3' },
  { name: 'A#4', file: 'b80.mp3' },
  { name: 'C#5', file: 'b83.mp3' },
  { name: 'D#5', file: 'b68.mp3' },
  { name: 'F#5', file: 'b71.mp3' },
  { name: 'G#5', file: 'b72.mp3' },
  { name: 'A#5', file: 'b74.mp3' },
  { name: 'C#6', file: 'b76.mp3' },
  { name: 'D#6', file: 'b90.mp3' },
  { name: 'F#6', file: 'b67.mp3' },
  { name: 'G#6', file: 'b86.mp3' },
  { name: 'A#6', file: 'b66.mp3' }
]